services:

  api:
    build:
      context: ./api_backend
      dockerfile: Dockerfile
    container_name: tourism_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://tourism:tourism123@tourism_db/tourism_dw
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    networks:
      - tourism_net
    depends_on:
      - postgres
      - minio

  nextjs:
    build:
      context: ./dashboard/nextjs-app
      dockerfile: Dockerfile.prod
    container_name: tourism_frontend
    command: npm start
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: "http://localhost:8000/api/v1"
      INTERNAL_API_URL: "http://tourism_api:8000/api/v1"
    networks:
      - tourism_net
    depends_on:
      - api

  postgres:
    image: postgres:15
    container_name: tourism_db
    environment:
      POSTGRES_USER: tourism
      POSTGRES_PASSWORD: tourism123
      POSTGRES_DB: tourism_dw
    ports:
      - "5432:5432"
    networks:
      - tourism_net
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data_warehouse/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql

  minio:
    image: minio/minio
    container_name: tourism_datalake
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - tourism_net
    volumes:
      - miniodata:/data

networks:
  tourism_net:
    driver: bridge

volumes:
  pgdata:
  miniodata:
